# Tensor Flow 2.0

## Features
1. High Level Keras API
2. Eager Exexcution - Like normal python, no Session

## Setup
conda install -c anaconda tensorflow-gpu==2.0.0

In [1]:
import tensorflow as tf
tf.__version__

'2.0.0'

In [2]:
# 初始化随机种子, 保证结果可重复
RANDOM_SEED = 42
tf.random.set_seed(RANDOM_SEED)

## Tensors
1. data container
2. abbitray dimension(scaler, vector, matrix)
3. float or int, string

In [5]:
x = tf.constant(1)
print(x)

tf.Tensor(1, shape=(), dtype=int32)


In [7]:
# 转换为numpy
x.numpy()

1

In [8]:
m = tf.constant([[1, 2, 1], [3, 4, 2]])
m

<tf.Tensor: id=2, shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 1],
       [3, 4, 2]])>

## Helpers

In [9]:
ones = tf.ones([3, 3])
ones

<tf.Tensor: id=5, shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [13]:
zeros = tf.zeros([2, 3])
zeros

<tf.Tensor: id=15, shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [14]:
tf.reshape(zeros, [3, 2])
zeros

<tf.Tensor: id=15, shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [15]:
# 转置
tf.transpose(zeros)
zeros

<tf.Tensor: id=15, shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

## Tensor Math

In [16]:
a = tf.constant(1)
b = tf.constant(1)
tf.add(a, b).numpy()

2

In [17]:
(a+b).numpy()

2

In [18]:
d1 = tf.constant([[1, 2], [1, 2]]);
d2 = tf.constant([[3, 4], [3, 4]]);
tf.tensordot(d1, d2, axes=1).numpy()

array([[ 9, 12],
       [ 9, 12]])

## Sampling